server:
  servlet:
    context-path: /hussar_v8
spring:
  profiles: show
  redis:
    host: redis.jxdinfo.com
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 3
        max-wait: -1
        max-idle: 3
        min-idle: 0
    timeout: 0
  datasource:
    url: jdbc:mysql://mysql.jxdinfo.com:3306/hussar?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: hussar
    password: Hussar@1
    db-name: hussar
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver